apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  name: mysql-label-backupplan
spec:
  backupNamespace: default
  backupConfig:
    target:
      name: annetterh
  backupPlanComponents:
    custom:
      - matchLabels:
          app: k8s-demo-app